name: pcalc_expression_engine
description: Backend orchestration for pcalc express expression evaluation.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  dart_clang_constexpr:
    git:
      url: https://github.com/richyo-codes/dart-clang-constexpr.git
      ref: 4157a4d968f1fdcde7f10904472cd29d22c70fc2
  tinyexpr_plusplus_ffi:
    git:
      url: https://github.com/richyo-codes/dart-tinyexpr-plusplus-ffi.git
      ref: dc249624c25226406b527a967144e5acf463d0e8
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
